import { 
  Candidate, 
  FollowUpRecord, 
  InterviewRecord, 
  JobOpening, 
  SourceAdSpend, 
  SystemSettings, 
  UserProfile, 
  AuditLogEntry, 
  TrainingRecord,
  Company,
  DepartmentItem,
  TargetSetting,
  RolePermissionsMap,
  TermsClause,
  OfferLetter
} from './types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Essential Soul Lifestyle Pvt Ltd',
    code: 'ESL',
    legalName: 'Essential Soul Lifestyle Private Limited',
    cin: 'U74999UP2022PTC168921',
    gstin: '09AAECE1234F1Z5',
    address: 'Plot A-40, ITHUM Tower, Block A, Sector 62',
    city: 'Noida',
    state: 'Uttar Pradesh',
    pincode: '201309',
    email: 'info@essentialsoul.com',
    phone: '+91 98765 43210',
    website: 'https://essentialsoul.com',
    departments: ['HR Recruitment', 'Management', 'Digital Marketing'],
    isActive: true,
    createdAt: '2024-01-15T09:00:00Z',
    adminUserId: 'esl.admin',
    adminPassword: 'ESL@Corp2026',
    masterContactPerson: 'Aditya Mathur (Director)',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
  {
    id: 'comp-2',
    name: 'BKD Retail & Lifestyle Pvt Ltd',
    code: 'BKD',
    legalName: 'BKD Lifestyle & Retail Private Limited',
    cin: 'U52100DL2023PTC189432',
    gstin: '07AABCB9876K1Z2',
    address: 'B-12, Sector 63, Near Electronic City Metro',
    city: 'Noida',
    state: 'Uttar Pradesh',
    pincode: '201301',
    email: 'careers@bkdlifestyle.com',
    phone: '+91 98111 22334',
    website: 'https://bkdlifestyle.com',
    departments: ['BKD Recruitment', 'Retail Store Operations', 'Calling Center'],
    isActive: true,
    createdAt: '2024-06-01T10:00:00Z',
    adminUserId: 'bkd.admin',
    adminPassword: 'BKD@Corp2026',
    masterContactPerson: 'Pooja Verma (Managing Head)',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
  {
    id: 'comp-3',
    name: 'Soul Organic Wellness LLP',
    code: 'SOW',
    legalName: 'Soul Organic Wellness Limited Liability Partnership',
    cin: 'AAY-9821',
    gstin: '09AAHCS4321E1Z9',
    address: 'C-24, Okhla Phase 3, Industrial Area',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110020',
    email: 'hr@soulorganic.in',
    phone: '+91 98999 55443',
    website: 'https://soulorganic.in',
    departments: ['Wellness Operations', 'Customer Care'],
    isActive: true,
    createdAt: '2025-02-10T11:00:00Z',
    adminUserId: 'sow.admin',
    adminPassword: 'SOW@Corp2026',
    masterContactPerson: 'Sunita Yadav (Partner)',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
];

export const INITIAL_DEPARTMENTS: DepartmentItem[] = [
  {
    id: 'dept-1',
    name: 'HR Recruitment',
    code: 'HR-REC',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    headName: 'Nandani',
    headEmail: 'nandani.hr@essentialsoul.com',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    description: 'Corporate HR talent acquisition team responsible for core office and sales staffing.',
    isActive: true,
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'dept-2',
    name: 'BKD Recruitment',
    code: 'BKD-REC',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    headName: 'Shivani',
    headEmail: 'shivani.bkd@essentialsoul.com',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    description: 'Outbound telecalling, retail, and field recruitment team for BKD subsidiaries.',
    isActive: true,
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'dept-3',
    name: 'Management',
    code: 'MGMT',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    headName: 'Aditya Mathur',
    headEmail: 'aditya.management@essentialsoul.com',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    description: 'Executive management, leadership oversight, strategic target monitoring.',
    isActive: true,
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'dept-4',
    name: 'Retail Store Operations',
    code: 'RTL-OPS',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    headName: 'Vikram Singh',
    headEmail: 'vikram.interviewer@essentialsoul.com',
    dailyInterviewTarget: 3,
    monthlyActiveJoiningTarget: 10,
    description: 'Retail stores, floor supervisors, inventory and showroom attendants.',
    isActive: true,
    createdAt: '2025-01-10T10:00:00Z',
  },
];

export const INITIAL_TARGET_SETTINGS: TargetSetting[] = [
  {
    id: 'tgt-1',
    targetType: 'Company',
    targetEntityId: 'comp-1',
    targetEntityName: 'Essential Soul Lifestyle Pvt Ltd',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-2',
    targetType: 'Company',
    targetEntityId: 'comp-2',
    targetEntityName: 'BKD Retail & Lifestyle Pvt Ltd',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-3',
    targetType: 'Department',
    targetEntityId: 'dept-1',
    targetEntityName: 'HR Recruitment (Nandani)',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-4',
    targetType: 'Department',
    targetEntityId: 'dept-1',
    targetEntityName: 'HR Recruitment (Nandani)',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 3,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-5',
    targetType: 'Department',
    targetEntityId: 'dept-2',
    targetEntityName: 'BKD Recruitment (Shivani)',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-6',
    targetType: 'Department',
    targetEntityId: 'dept-2',
    targetEntityName: 'BKD Recruitment (Shivani)',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 3,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-7',
    targetType: 'HR Executive',
    targetEntityId: 'usr-1',
    targetEntityName: 'Nandani',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 4,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-8',
    targetType: 'HR Executive',
    targetEntityId: 'usr-1',
    targetEntityName: 'Nandani',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 16,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-9',
    targetType: 'HR Executive',
    targetEntityId: 'usr-2',
    targetEntityName: 'Shivani',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 4,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-10',
    targetType: 'HR Executive',
    targetEntityId: 'usr-2',
    targetEntityName: 'Shivani',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 16,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-1',
    name: 'Nandani',
    email: 'nandani.hr@essentialsoul.com',
    phone: '+91 98765 00001',
    userId: 'nandani.hr',
    password: 'Nandani@2026',
    role: 'HR Head',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-08-15T10:30:00Z',
  },
  {
    id: 'usr-2',
    name: 'Shivani',
    email: 'shivani.bkd@essentialsoul.com',
    phone: '+91 98765 00002',
    userId: 'shivani.bkd',
    password: 'Shivani@2026',
    role: 'HR Executive',
    department: 'BKD Recruitment',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    status: 'Active',
    createdAt: '2024-06-01T10:00:00Z',
    lastPasswordChanged: '2026-08-20T11:15:00Z',
  },
  {
    id: 'usr-3',
    name: 'Aditya Mathur',
    email: 'aditya.management@essentialsoul.com',
    phone: '+91 98765 00000',
    userId: 'aditya.mathur',
    password: 'Aditya@2026',
    role: 'Director / Management',
    department: 'Management',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
  {
    id: 'usr-4',
    name: 'Super Admin',
    email: 'admin@essentialsoul.com',
    phone: '+91 98765 00003',
    userId: 'admin',
    password: 'Admin@2026',
    role: 'Super Admin',
    department: 'Management',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-09-01T08:00:00Z',
  },
  {
    id: 'usr-5',
    name: 'Vikram Singh',
    email: 'vikram.interviewer@essentialsoul.com',
    phone: '+91 98765 00004',
    userId: 'vikram.singh',
    password: 'Vikram@2026',
    role: 'Interviewer',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 3,
    monthlyActiveJoiningTarget: 10,
    status: 'Active',
    createdAt: '2024-03-10T11:00:00Z',
    lastPasswordChanged: '2026-08-10T14:20:00Z',
  },
];

export const DEFAULT_POSITIONS: string[] = [
  'Sales Executive',
  'Telecaller',
  'HR Executive',
  'Team Leader',
  'Digital Marketing Executive',
  'Back Office Executive',
  'Customer Support Executive',
  'Calling Executive',
  'Operations Executive',
];

export const INITIAL_SETTINGS: SystemSettings = {
  activeJoiningDaysThreshold: 7,
  companyName: 'Essential Soul Lifestyle Pvt Ltd',
  companyAddress: 'Sector 62, Noida, Uttar Pradesh, 201309',
  companyPhone: '+91 98765 43210',
};

// Today's date reference
export const TODAY = '2026-09-04';
export const YESTERDAY = '2026-09-03';
export const TWO_DAYS_AGO = '2026-09-02';
export const SEVEN_DAYS_AGO = '2026-08-28';
export const TEN_DAYS_AGO = '2026-08-25';

export const INITIAL_CANDIDATES: Candidate[] = [];

export const INITIAL_FOLLOW_UPS: FollowUpRecord[] = [];

export const INITIAL_INTERVIEWS: InterviewRecord[] = [];

export const INITIAL_JOB_OPENINGS: JobOpening[] = [
  {
    id: 'job-1',
    jobTitle: 'Sales Executive',
    department: 'HR Recruitment',
    vacancies: 10,
    filledPositions: 4,
    salaryRange: '₹20,000 - ₹28,000 + Incentives',
    jobLocation: 'Sector 62, Noida',
    experience: '1-3 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-30',
    status: 'Urgent',
  },
  {
    id: 'job-2',
    jobTitle: 'Telecaller',
    department: 'BKD Recruitment',
    vacancies: 15,
    filledPositions: 8,
    salaryRange: '₹16,000 - ₹22,000 + Incentives',
    jobLocation: 'Sector 62, Noida',
    experience: '0-2 Years',
    hrResponsible: 'Shivani',
    hiringDeadline: '2026-09-25',
    status: 'Open',
  },
  {
    id: 'job-3',
    jobTitle: 'HR Executive',
    department: 'HR Recruitment',
    vacancies: 2,
    filledPositions: 1,
    salaryRange: '₹22,000 - ₹28,000',
    jobLocation: 'Sector 62, Noida',
    experience: '1-2 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-20',
    status: 'Open',
  },
  {
    id: 'job-4',
    jobTitle: 'Team Leader',
    department: 'BKD Recruitment',
    vacancies: 3,
    filledPositions: 1,
    salaryRange: '₹32,000 - ₹40,000',
    jobLocation: 'Sector 62, Noida',
    experience: '3-5 Years',
    hrResponsible: 'Shivani',
    hiringDeadline: '2026-09-18',
    status: 'Urgent',
  },
  {
    id: 'job-5',
    jobTitle: 'Digital Marketing Executive',
    department: 'HR Recruitment',
    vacancies: 2,
    filledPositions: 0,
    salaryRange: '₹25,000 - ₹35,000',
    jobLocation: 'Sector 62, Noida',
    experience: '2-4 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-30',
    status: 'Open',
  },
  {
    id: 'job-6',
    jobTitle: 'Back Office Executive',
    department: 'HR Recruitment',
    vacancies: 4,
    filledPositions: 2,
    salaryRange: '₹18,000 - ₹24,000',
    jobLocation: 'Sector 62, Noida',
    experience: '1-2 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-22',
    status: 'Open',
  },
];

export const INITIAL_SOURCE_AD_SPENDS: SourceAdSpend[] = [
  { source: 'Meta Ads', adSpend: 35000 },
  { source: 'Facebook', adSpend: 15000 },
  { source: 'Instagram', adSpend: 18000 },
  { source: 'WhatsApp', adSpend: 5000 },
  { source: 'Indeed', adSpend: 22000 },
  { source: 'Naukri', adSpend: 28000 },
  { source: 'Apna', adSpend: 16000 },
  { source: 'WorkIndia', adSpend: 12000 },
  { source: 'Referral', adSpend: 4000 },
  { source: 'Walk-in', adSpend: 0 },
  { source: 'Data Vendor', adSpend: 15000 },
  { source: 'Existing Database', adSpend: 0 },
  { source: 'Other', adSpend: 2000 },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [];

export const DEFAULT_ROLE_PERMISSIONS: RolePermissionsMap = {
  'Super Admin': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'users',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'Director / Management': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'users',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'HR Head': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'Team Leader': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'targets',
    'import-export',
    'reports',
    'templates',
  ],
  'HR Executive': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'import-export',
    'templates',
  ],
  'Recruiter': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'import-export',
    'templates',
  ],
  'Interviewer': [
    'dashboard',
    'interviews',
    'candidates',
    'jobs',
    'terms-conditions',
  ],
};

export const INITIAL_TERMS_CLAUSES: TermsClause[] = [
  {
    id: 'tc-1',
    clauseNumber: '1.0',
    category: 'Probation & Confirmation',
    title: 'Probationary Period & Evaluation',
    content: 'The employee shall be on probation for an initial period of 90 (ninety) calendar days from the Date of Joining. During this period, performance, discipline, adherence to operational calling targets, and team alignment will be reviewed on a continuous monthly basis. The company reserves the absolute right to extend the probation period or dispense with services if benchmark standards are not satisfactorily met.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-2',
    clauseNumber: '2.0',
    category: 'Working Hours & Attendance',
    title: 'Operating Hours, Shifts & Biometric Attendance',
    content: 'Standard operational working hours are Monday through Saturday from 9:30 AM to 6:30 PM with a designated 45-minute lunch break. Punctuality is strictly enforced; daily attendance must be marked via the biometric sensor or registered mobile ATS application. Three unexcused tardy arrivals exceeding 15 minutes within a calendar month shall result in the forfeiture of half a day of casual leave.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-3',
    clauseNumber: '3.0',
    category: 'Compensation & Incentives',
    title: 'Payroll Disbursement Cycle & Target-Linked Incentives',
    content: 'Salary is disbursed monthly on or before the 7th calendar day following the payroll cycle directly into the registered bank account. Remuneration is subject to all statutory deductions including TDS, Employee Provident Fund (EPF), Employee State Insurance (ESIC), and Professional Tax where applicable. Variable performance incentives are calculated strictly based on verified active candidate joinings sustaining beyond the 7-day threshold.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-4',
    clauseNumber: '4.0',
    category: 'Code of Conduct',
    title: 'Professional Integrity, Workplace Decorum & POSH Policy',
    content: 'The employee agrees to observe the highest standards of professional conduct, truthfulness, and decorum at all times. The company enforces strict zero-tolerance towards sexual harassment, verbal abuse, hate speech, insubordination, or discrimination in strict accordance with the Prevention of Sexual Harassment of Women at Workplace (POSH) Act 2013.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-5',
    clauseNumber: '5.0',
    category: 'Confidentiality & NDA',
    title: 'Proprietary Candidate Databases, Client Data & Non-Disclosure',
    content: 'The employee shall maintain absolute confidentiality regarding candidate resumes, mobile numbers, WhatsApp transcripts, client contracts, commercial recruitment fee structures, and internal candidate pipelining metrics. All such materials remain exclusive trade secrets of Essential Soul Lifestyle Pvt Ltd and must never be extracted, photographed, forwarded, or utilized outside company business.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-6',
    clauseNumber: '6.0',
    category: 'Leave & Time Off',
    title: 'Leave Accrual & Prior Approval Guidelines',
    content: 'Subsequent to successful confirmation post-probation, the employee is entitled to 18 (eighteen) days of paid leave annually, accrued at 1.5 days per completed calendar month. Any planned absence must be submitted in the recruitment portal at least 48 hours in advance and sanctioned in writing by the Team Leader or Department Head. Unsanctioned absence exceeding 3 consecutive days will be considered job abandonment.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-7',
    clauseNumber: '7.0',
    category: 'Termination & Notice',
    title: 'Notice Period, Separation Formalities & Full and Final Settlement',
    content: 'During the probationary period, either party may terminate this employment contract by providing 15 (fifteen) calendar days notice in writing or gross salary in lieu thereof. Upon confirmation, the notice period shall be 30 (thirty) calendar days. The employee must complete a formal handover of all pending candidate pipeline leads, client files, and company equipment prior to release of Full & Final (F&F) settlement.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-8',
    clauseNumber: '8.0',
    category: 'Onboarding Documents',
    title: 'Credential Verification & Mandatory Submission Checklist',
    content: 'This offer of employment is contingent upon prompt receipt and background verification of mandatory documents: self-attested copies of Aadhaar Card, PAN Card, Graduation/Post-Graduation Degree & Final Marksheet, Relieving/Experience Letter from prior employer, last 3 months salary slips/bank statements, and 3 passport-sized color photographs.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Shivani (HR Executive)',
  },
];

export const INITIAL_OFFER_LETTERS: OfferLetter[] = [];
