import { 
  Candidate, 
  FollowUpRecord, 
  InterviewRecord, 
  JobOpening, 
  SourceAdSpend, 
  SystemSettings, 
  UserProfile, 
  AuditLogEntry, 
  TrainingRecord,
  Company,
  DepartmentItem,
  TargetSetting,
  RolePermissionsMap,
  TermsClause,
  OfferLetter
} from './types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Essential Soul Lifestyle Pvt Ltd',
    code: 'ESL',
    legalName: 'Essential Soul Lifestyle Private Limited',
    cin: 'U74999UP2022PTC168921',
    gstin: '09AAECE1234F1Z5',
    address: 'Plot A-40, ITHUM Tower, Block A, Sector 62',
    city: 'Noida',
    state: 'Uttar Pradesh',
    pincode: '201309',
    email: 'info@essentialsoul.com',
    phone: '+91 98765 43210',
    website: 'https://essentialsoul.com',
    departments: ['HR Recruitment', 'Management', 'Digital Marketing'],
    isActive: true,
    createdAt: '2024-01-15T09:00:00Z',
    adminUserId: 'esl.admin',
    adminPassword: 'ESL@Corp2026',
    masterContactPerson: 'Aditya Mathur (Director)',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
  {
    id: 'comp-2',
    name: 'BKD Retail & Lifestyle Pvt Ltd',
    code: 'BKD',
    legalName: 'BKD Lifestyle & Retail Private Limited',
    cin: 'U52100DL2023PTC189432',
    gstin: '07AABCB9876K1Z2',
    address: 'B-12, Sector 63, Near Electronic City Metro',
    city: 'Noida',
    state: 'Uttar Pradesh',
    pincode: '201301',
    email: 'careers@bkdlifestyle.com',
    phone: '+91 98111 22334',
    website: 'https://bkdlifestyle.com',
    departments: ['BKD Recruitment', 'Retail Store Operations', 'Calling Center'],
    isActive: true,
    createdAt: '2024-06-01T10:00:00Z',
    adminUserId: 'bkd.admin',
    adminPassword: 'BKD@Corp2026',
    masterContactPerson: 'Pooja Verma (Managing Head)',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
  {
    id: 'comp-3',
    name: 'Soul Organic Wellness LLP',
    code: 'SOW',
    legalName: 'Soul Organic Wellness Limited Liability Partnership',
    cin: 'AAY-9821',
    gstin: '09AAHCS4321E1Z9',
    address: 'C-24, Okhla Phase 3, Industrial Area',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110020',
    email: 'hr@soulorganic.in',
    phone: '+91 98999 55443',
    website: 'https://soulorganic.in',
    departments: ['Wellness Operations', 'Customer Care'],
    isActive: true,
    createdAt: '2025-02-10T11:00:00Z',
    adminUserId: 'sow.admin',
    adminPassword: 'SOW@Corp2026',
    masterContactPerson: 'Sunita Yadav (Partner)',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
];

export const INITIAL_DEPARTMENTS: DepartmentItem[] = [
  {
    id: 'dept-1',
    name: 'HR Recruitment',
    code: 'HR-REC',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    headName: 'Nandani',
    headEmail: 'nandani.hr@essentialsoul.com',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    description: 'Corporate HR talent acquisition team responsible for core office and sales staffing.',
    isActive: true,
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'dept-2',
    name: 'BKD Recruitment',
    code: 'BKD-REC',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    headName: 'Shivani',
    headEmail: 'shivani.bkd@essentialsoul.com',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    description: 'Outbound telecalling, retail, and field recruitment team for BKD subsidiaries.',
    isActive: true,
    createdAt: '2024-06-01T10:00:00Z',
  },
  {
    id: 'dept-3',
    name: 'Management',
    code: 'MGMT',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    headName: 'Aditya Mathur',
    headEmail: 'aditya.management@essentialsoul.com',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    description: 'Executive management, leadership oversight, strategic target monitoring.',
    isActive: true,
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'dept-4',
    name: 'Retail Store Operations',
    code: 'RTL-OPS',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    headName: 'Vikram Singh',
    headEmail: 'vikram.interviewer@essentialsoul.com',
    dailyInterviewTarget: 3,
    monthlyActiveJoiningTarget: 10,
    description: 'Retail stores, floor supervisors, inventory and showroom attendants.',
    isActive: true,
    createdAt: '2025-01-10T10:00:00Z',
  },
];

export const INITIAL_TARGET_SETTINGS: TargetSetting[] = [
  {
    id: 'tgt-1',
    targetType: 'Company',
    targetEntityId: 'comp-1',
    targetEntityName: 'Essential Soul Lifestyle Pvt Ltd',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-2',
    targetType: 'Company',
    targetEntityId: 'comp-2',
    targetEntityName: 'BKD Retail & Lifestyle Pvt Ltd',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-3',
    targetType: 'Department',
    targetEntityId: 'dept-1',
    targetEntityName: 'HR Recruitment (Nandani)',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-4',
    targetType: 'Department',
    targetEntityId: 'dept-1',
    targetEntityName: 'HR Recruitment (Nandani)',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 3,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-5',
    targetType: 'Department',
    targetEntityId: 'dept-2',
    targetEntityName: 'BKD Recruitment (Shivani)',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 15,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-6',
    targetType: 'Department',
    targetEntityId: 'dept-2',
    targetEntityName: 'BKD Recruitment (Shivani)',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 3,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-7',
    targetType: 'HR Executive',
    targetEntityId: 'usr-1',
    targetEntityName: 'Nandani',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 4,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-8',
    targetType: 'HR Executive',
    targetEntityId: 'usr-1',
    targetEntityName: 'Nandani',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 16,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-9',
    targetType: 'HR Executive',
    targetEntityId: 'usr-2',
    targetEntityName: 'Shivani',
    period: 'Daily',
    metric: 'Interviews Conducted',
    targetValue: 5,
    minimumBenchmark: 4,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
  {
    id: 'tgt-10',
    targetType: 'HR Executive',
    targetEntityId: 'usr-2',
    targetEntityName: 'Shivani',
    period: 'Monthly',
    metric: 'Active Joinings',
    targetValue: 20,
    minimumBenchmark: 16,
    updatedAt: '2026-09-01T00:00:00Z',
    updatedBy: 'Aditya Mathur',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-1',
    name: 'Nandani',
    email: 'nandani.hr@essentialsoul.com',
    phone: '+91 98765 00001',
    userId: 'nandani.hr',
    password: 'Nandani@2026',
    role: 'HR Head',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-08-15T10:30:00Z',
  },
  {
    id: 'usr-2',
    name: 'Shivani',
    email: 'shivani.bkd@essentialsoul.com',
    phone: '+91 98765 00002',
    userId: 'shivani.bkd',
    password: 'Shivani@2026',
    role: 'HR Executive',
    department: 'BKD Recruitment',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    dailyInterviewTarget: 5,
    monthlyActiveJoiningTarget: 20,
    status: 'Active',
    createdAt: '2024-06-01T10:00:00Z',
    lastPasswordChanged: '2026-08-20T11:15:00Z',
  },
  {
    id: 'usr-3',
    name: 'Aditya Mathur',
    email: 'aditya.management@essentialsoul.com',
    phone: '+91 98765 00000',
    userId: 'aditya.mathur',
    password: 'Aditya@2026',
    role: 'Director / Management',
    department: 'Management',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-09-01T09:00:00Z',
  },
  {
    id: 'usr-4',
    name: 'Super Admin',
    email: 'admin@essentialsoul.com',
    phone: '+91 98765 00003',
    userId: 'admin',
    password: 'Admin@2026',
    role: 'Super Admin',
    department: 'Management',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 0,
    monthlyActiveJoiningTarget: 0,
    status: 'Active',
    createdAt: '2024-01-15T09:00:00Z',
    lastPasswordChanged: '2026-09-01T08:00:00Z',
  },
  {
    id: 'usr-5',
    name: 'Vikram Singh',
    email: 'vikram.interviewer@essentialsoul.com',
    phone: '+91 98765 00004',
    userId: 'vikram.singh',
    password: 'Vikram@2026',
    role: 'Interviewer',
    department: 'HR Recruitment',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    dailyInterviewTarget: 3,
    monthlyActiveJoiningTarget: 10,
    status: 'Active',
    createdAt: '2024-03-10T11:00:00Z',
    lastPasswordChanged: '2026-08-10T14:20:00Z',
  },
];

export const DEFAULT_POSITIONS: string[] = [
  'Sales Executive',
  'Telecaller',
  'HR Executive',
  'Team Leader',
  'Digital Marketing Executive',
  'Back Office Executive',
  'Customer Support Executive',
  'Calling Executive',
  'Operations Executive',
];

export const INITIAL_SETTINGS: SystemSettings = {
  activeJoiningDaysThreshold: 7,
  companyName: 'Essential Soul Lifestyle Pvt Ltd',
  companyAddress: 'Sector 62, Noida, Uttar Pradesh, 201309',
  companyPhone: '+91 98765 43210',
};

// Today's date reference
export const TODAY = '2026-09-04';
export const YESTERDAY = '2026-09-03';
export const TWO_DAYS_AGO = '2026-09-02';
export const SEVEN_DAYS_AGO = '2026-08-28';
export const TEN_DAYS_AGO = '2026-08-25';

export const INITIAL_CANDIDATES: Candidate[] = [
  // 1. New Lead - Uncontacted
  {
    id: 'ESL-2026-001',
    fullName: 'Rahul Sharma',
    mobileNumber: '9871122334',
    whatsappNumber: '9871122334',
    gender: 'Male',
    age: 24,
    dateOfBirth: '2002-03-15',
    email: 'rahul.sharma@gmail.com',
    city: 'Noida',
    area: 'Sector 62',
    address: 'Flat 402, Block B, Indirapuram',
    positionApplied: 'Sales Executive',
    department: 'HR Recruitment',
    qualification: 'Graduate (B.Com)',
    totalExperience: '1.5 Years',
    relevantExperience: '1 Year in Outbound Sales',
    currentCompany: 'Apex Retail',
    currentSalary: 18000,
    expectedSalary: 24000,
    noticePeriod: 'Immediate',
    preferredLocation: 'Noida',
    candidateSource: 'Meta Ads',
    assignedHr: 'Nandani',
    remarks: 'Good communication, looking for day shift',
    status: 'New Lead',
    createdAt: `${TODAY}T09:30:00Z`,
    lastActivityDate: `${TODAY}T09:30:00Z`,
  },
  // 2. Connected & Follow-up Due Today
  {
    id: 'ESL-2026-002',
    fullName: 'Pooja Verma',
    mobileNumber: '9810987654',
    whatsappNumber: '9810987654',
    gender: 'Female',
    age: 23,
    dateOfBirth: '2003-07-20',
    email: 'pooja.verma23@yahoo.com',
    city: 'Ghaziabad',
    area: 'Vaishali',
    positionApplied: 'Telecaller',
    department: 'BKD Recruitment',
    qualification: '12th Pass + Pursuing BA',
    totalExperience: '1 Year',
    relevantExperience: '1 Year Domestic BPO',
    currentCompany: 'Vision Call Center',
    currentSalary: 15000,
    expectedSalary: 19000,
    noticePeriod: 'Immediate',
    candidateSource: 'WorkIndia',
    assignedHr: 'Shivani',
    remarks: 'Hindi & English both fluent',
    status: 'Follow-up',
    createdAt: `${YESTERDAY}T11:00:00Z`,
    firstCallDate: `${YESTERDAY}T11:30:00Z`,
    lastActivityDate: `${TODAY}T10:15:00Z`,
  },
  // 3. Overdue Follow-up (Yesterday's follow-up missed)
  {
    id: 'ESL-2026-003',
    fullName: 'Aman Deep',
    mobileNumber: '9911223344',
    whatsappNumber: '9911223344',
    gender: 'Male',
    age: 26,
    email: 'amandeep.voice@gmail.com',
    city: 'Delhi',
    area: 'Laxmi Nagar',
    positionApplied: 'Calling Executive',
    department: 'HR Recruitment',
    qualification: 'BBA',
    totalExperience: '2 Years',
    relevantExperience: '2 Years Telemarketing',
    currentSalary: 20000,
    expectedSalary: 25000,
    candidateSource: 'Naukri',
    assignedHr: 'Nandani',
    remarks: 'Asked to call back on 3rd Sept 4 PM',
    status: 'Call Back',
    createdAt: `${TWO_DAYS_AGO}T14:00:00Z`,
    firstCallDate: `${TWO_DAYS_AGO}T14:30:00Z`,
    lastActivityDate: `${TWO_DAYS_AGO}T15:00:00Z`,
  },
  // 4. Interview Scheduled for Today
  {
    id: 'ESL-2026-004',
    fullName: 'Ritu Sen',
    mobileNumber: '9899123456',
    whatsappNumber: '9899123456',
    gender: 'Female',
    age: 25,
    email: 'ritu.sen@outlook.com',
    city: 'Noida',
    area: 'Sector 18',
    positionApplied: 'Customer Support Executive',
    department: 'HR Recruitment',
    qualification: 'Graduate (BCA)',
    totalExperience: '2 Years',
    relevantExperience: '1.5 Years in CRM support',
    currentSalary: 22000,
    expectedSalary: 27000,
    noticePeriod: '7 Days',
    candidateSource: 'Indeed',
    assignedHr: 'Nandani',
    remarks: 'Confirmed arrival for face to face round',
    status: 'Interview Confirmed',
    createdAt: `${TWO_DAYS_AGO}T10:00:00Z`,
    firstCallDate: `${TWO_DAYS_AGO}T11:00:00Z`,
    lastActivityDate: `${TODAY}T09:00:00Z`,
  },
  // 5. Interview Conducted Today (by Shivani) - Selected
  {
    id: 'ESL-2026-005',
    fullName: 'Kunal Chauhan',
    mobileNumber: '9818877665',
    whatsappNumber: '9818877665',
    gender: 'Male',
    age: 27,
    email: 'kunal.c@gmail.com',
    city: 'Delhi',
    area: 'Mayur Vihar',
    positionApplied: 'Team Leader',
    department: 'BKD Recruitment',
    qualification: 'MBA Marketing',
    totalExperience: '4 Years',
    relevantExperience: '2.5 Years as Assistant TL',
    currentCompany: 'TeleServices Ltd',
    currentSalary: 32000,
    expectedSalary: 38000,
    noticePeriod: '15 Days',
    candidateSource: 'Apna',
    assignedHr: 'Shivani',
    remarks: 'Strong team handling experience, rated 4.5/5',
    status: 'Selected',
    salaryOffered: 36000,
    selectionDate: TODAY,
    joiningDate: '2026-09-10',
    documentsStatus: 'Pending',
    joiningConfirmation: true,
    joiningStatus: 'Confirmed',
    createdAt: `${SEVEN_DAYS_AGO}T10:00:00Z`,
    firstCallDate: `${SEVEN_DAYS_AGO}T10:30:00Z`,
    lastActivityDate: `${TODAY}T11:30:00Z`,
  },
  // 6. Selected / Pre-Joining Stage (Waiting for documents)
  {
    id: 'ESL-2026-006',
    fullName: 'Sneha Kapur',
    mobileNumber: '9873344556',
    whatsappNumber: '9873344556',
    gender: 'Female',
    age: 24,
    email: 'sneha.k@gmail.com',
    city: 'Noida',
    area: 'Sector 50',
    positionApplied: 'HR Executive',
    department: 'HR Recruitment',
    qualification: 'MBA HR',
    totalExperience: '1 Year',
    relevantExperience: '1 Year in Sourcing',
    currentSalary: 20000,
    expectedSalary: 25000,
    candidateSource: 'Referral',
    assignedHr: 'Nandani',
    remarks: 'Document verification in progress',
    status: 'Joining Confirmed',
    salaryOffered: 24000,
    selectionDate: `${TWO_DAYS_AGO}`,
    joiningDate: '2026-09-08',
    reportingTime: '09:30 AM',
    reportingManager: 'Nandani (HR Head)',
    officeLocation: 'Essential Soul HQ, Sector 62',
    documentsStatus: 'Partial',
    joiningConfirmation: true,
    joiningStatus: 'Confirmed',
    createdAt: `${SEVEN_DAYS_AGO}T12:00:00Z`,
    firstCallDate: `${SEVEN_DAYS_AGO}T14:00:00Z`,
    lastActivityDate: `${TODAY}T10:00:00Z`,
  },
  // 7. Joined - Completed 8 Days -> Ready for Active Joining!
  {
    id: 'ESL-2026-007',
    fullName: 'Ankit Tiwari',
    mobileNumber: '9891238899',
    whatsappNumber: '9891238899',
    gender: 'Male',
    age: 25,
    email: 'ankit.tiwari@gmail.com',
    city: 'Noida',
    area: 'Sector 15',
    positionApplied: 'Sales Executive',
    department: 'HR Recruitment',
    qualification: 'Graduate',
    totalExperience: '2 Years',
    relevantExperience: '1.5 Years in Lifestyle Sales',
    currentSalary: 22000,
    expectedSalary: 26000,
    candidateSource: 'Meta Ads',
    assignedHr: 'Nandani',
    remarks: 'Joined on 27th Aug, completed 8 days of good performance',
    status: 'Joined',
    salaryOffered: 25000,
    selectionDate: '2026-08-20',
    joiningDate: '2026-08-27',
    actualJoinedDate: '2026-08-27',
    documentsStatus: 'Verified',
    joiningConfirmation: true,
    joiningStatus: 'Joined',
    isActiveJoining: false, // Can now be marked Active Joining!
    createdAt: '2026-08-15T09:00:00Z',
    lastActivityDate: `${TODAY}T09:00:00Z`,
  },
  // 8. Active Joining (Contributes to Shivani's target)
  {
    id: 'ESL-2026-008',
    fullName: 'Megha Gupta',
    mobileNumber: '9811009988',
    whatsappNumber: '9811009988',
    gender: 'Female',
    age: 23,
    email: 'megha.gupta@gmail.com',
    city: 'Delhi',
    area: 'Preet Vihar',
    positionApplied: 'Telecaller',
    department: 'BKD Recruitment',
    qualification: 'Graduate',
    totalExperience: '1 Year',
    relevantExperience: '1 Year BPO',
    candidateSource: 'Instagram',
    assignedHr: 'Shivani',
    remarks: 'Active employee, regular attendance and hitting calling targets',
    status: 'Active Joining',
    salaryOffered: 18000,
    selectionDate: '2026-08-10',
    joiningDate: '2026-08-18',
    actualJoinedDate: '2026-08-18',
    activeJoinedDate: '2026-08-26',
    documentsStatus: 'Verified',
    joiningConfirmation: true,
    joiningStatus: 'Joined',
    isActiveJoining: true,
    createdAt: '2026-08-05T10:00:00Z',
    lastActivityDate: '2026-08-26T17:00:00Z',
  },
  // 9. Training Stage
  {
    id: 'ESL-2026-009',
    fullName: 'Vikas Malhotra',
    mobileNumber: '9810112244',
    whatsappNumber: '9810112244',
    gender: 'Male',
    age: 24,
    email: 'vikas.m@gmail.com',
    city: 'Noida',
    area: 'Sector 76',
    positionApplied: 'Back Office Executive',
    department: 'HR Recruitment',
    qualification: 'B.Com Graduate',
    totalExperience: '6 Months',
    relevantExperience: 'Excel & Data Processing',
    candidateSource: 'Facebook',
    assignedHr: 'Nandani',
    remarks: 'Undergoing internal CRM & ERP training',
    status: 'Training Started',
    trainingStatus: 'In Training',
    trainerName: 'Ashish Rawat',
    trainingStartDate: '2026-09-02',
    trainingEndDate: '2026-09-06',
    trainingScore: 82,
    createdAt: `${TEN_DAYS_AGO}T11:00:00Z`,
    lastActivityDate: `${TODAY}T11:00:00Z`,
  },
  // 10. No Show Candidate
  {
    id: 'ESL-2026-010',
    fullName: 'Mohit Rawat',
    mobileNumber: '9899001122',
    whatsappNumber: '9899001122',
    gender: 'Male',
    age: 22,
    email: 'mohit.r@gmail.com',
    city: 'Delhi',
    area: 'Shahdara',
    positionApplied: 'Calling Executive',
    department: 'BKD Recruitment',
    qualification: '12th Pass',
    totalExperience: 'Fresher',
    relevantExperience: 'None',
    candidateSource: 'Apna',
    assignedHr: 'Shivani',
    remarks: 'Did not arrive for scheduled interview on 2nd Sept. Phone switched off.',
    status: 'No Show',
    createdAt: `${SEVEN_DAYS_AGO}T10:00:00Z`,
    lastActivityDate: `${TWO_DAYS_AGO}T15:00:00Z`,
  },
  // 11. Resigned
  {
    id: 'ESL-2026-011',
    fullName: 'Siddharth Dave',
    mobileNumber: '9822334455',
    whatsappNumber: '9822334455',
    gender: 'Male',
    age: 28,
    email: 'sid.dave@gmail.com',
    city: 'Noida',
    area: 'Sector 12',
    positionApplied: 'Digital Marketing Executive',
    department: 'HR Recruitment',
    qualification: 'B.Tech',
    totalExperience: '3 Years',
    relevantExperience: 'Google & Meta Ads',
    candidateSource: 'Naukri',
    assignedHr: 'Nandani',
    remarks: 'Left after 4 days due to personal location constraints',
    status: 'Resigned',
    salaryOffered: 32000,
    selectionDate: '2026-08-15',
    joiningDate: '2026-08-22',
    actualJoinedDate: '2026-08-22',
    createdAt: '2026-08-10T10:00:00Z',
    lastActivityDate: '2026-08-28T17:00:00Z',
  },
  // 12. Aging Lead - Untouched for > 24 hours
  {
    id: 'ESL-2026-012',
    fullName: 'Divya Prakash',
    mobileNumber: '9876543219',
    whatsappNumber: '9876543219',
    gender: 'Female',
    age: 23,
    email: 'divya.p@gmail.com',
    city: 'Greater Noida',
    area: 'Pari Chowk',
    positionApplied: 'Operations Executive',
    department: 'BKD Recruitment',
    qualification: 'B.Sc',
    totalExperience: '1 Year',
    relevantExperience: 'Store Inventory Coordination',
    candidateSource: 'Indeed',
    assignedHr: 'Shivani',
    remarks: 'Lead received 2 days ago, not contacted yet!',
    status: 'Not Contacted',
    createdAt: `${TWO_DAYS_AGO}T11:00:00Z`,
    lastActivityDate: `${TWO_DAYS_AGO}T11:00:00Z`,
  },
];

export const INITIAL_FOLLOW_UPS: FollowUpRecord[] = [
  {
    id: 'fu-1',
    candidateId: 'ESL-2026-002',
    candidateName: 'Pooja Verma',
    candidateMobile: '9810987654',
    position: 'Telecaller',
    hrExecutive: 'Shivani',
    followUpDate: TODAY,
    followUpTime: '14:30',
    followUpMode: 'Call',
    candidateResponse: 'Interested, requested briefing on salary and work timings',
    notes: 'Confirm if she can attend interview tomorrow at 11 AM',
    nextFollowUpDate: TODAY,
    nextFollowUpTime: '14:30',
    resultingStatus: 'Follow-up',
    isCompleted: false,
    createdAt: `${YESTERDAY}T12:00:00Z`,
  },
  {
    id: 'fu-2',
    candidateId: 'ESL-2026-003',
    candidateName: 'Aman Deep',
    candidateMobile: '9911223344',
    position: 'Calling Executive',
    hrExecutive: 'Nandani',
    followUpDate: YESTERDAY, // OVERDUE!
    followUpTime: '16:00',
    followUpMode: 'Call',
    candidateResponse: 'Was in a meeting, asked to call back yesterday 4 PM',
    notes: 'Urgent follow-up overdue!',
    nextFollowUpDate: YESTERDAY,
    nextFollowUpTime: '16:00',
    resultingStatus: 'Call Back',
    isCompleted: false,
    createdAt: `${TWO_DAYS_AGO}T15:00:00Z`,
  },
  {
    id: 'fu-3',
    candidateId: 'ESL-2026-004',
    candidateName: 'Ritu Sen',
    candidateMobile: '9899123456',
    position: 'Customer Support Executive',
    hrExecutive: 'Nandani',
    followUpDate: TODAY,
    followUpTime: '10:00',
    followUpMode: 'WhatsApp',
    candidateResponse: 'Confirmed she will reach office by 11:30 AM',
    notes: 'Interview confirmed for today',
    resultingStatus: 'Interview Confirmed',
    isCompleted: true,
    createdAt: `${TODAY}T09:30:00Z`,
  },
];

export const INITIAL_INTERVIEWS: InterviewRecord[] = [
  {
    id: 'int-1',
    candidateId: 'ESL-2026-004',
    candidateName: 'Ritu Sen',
    candidateMobile: '9899123456',
    position: 'Customer Support Executive',
    department: 'HR Recruitment',
    hrExecutive: 'Nandani',
    interviewer: 'Vikram Singh',
    interviewDate: TODAY,
    interviewTime: '11:30',
    interviewMode: 'Office Interview',
    interviewLocation: 'Essential Soul HQ, Conference Room 2',
    attendanceStatus: 'Confirmed',
    reminderSent: true,
    remarks: 'First round technical & communication assessment',
    createdAt: `${TWO_DAYS_AGO}T16:00:00Z`,
  },
  {
    id: 'int-2',
    candidateId: 'ESL-2026-005',
    candidateName: 'Kunal Chauhan',
    candidateMobile: '9818877665',
    position: 'Team Leader',
    department: 'BKD Recruitment',
    hrExecutive: 'Shivani',
    interviewer: 'Aditya Mathur',
    interviewDate: TODAY,
    interviewTime: '10:30',
    interviewMode: 'Office Interview',
    interviewLocation: 'Cabin 3',
    attendanceStatus: 'Conducted',
    reminderSent: true,
    remarks: 'Conducted successfully, recommended for selection',
    evaluation: {
      communication: 4,
      confidence: 5,
      experience: 4,
      jobKnowledge: 5,
      stability: 4,
      salaryFit: 4,
      attitude: 5,
      overallSuitability: 5,
      averageRating: 4.5,
      finalResult: 'Selected',
      interviewerRemarks: 'Strong command over team management and KPIs. Selected for Team Leader position.',
      evaluatedAt: `${TODAY}T11:30:00Z`,
    },
    createdAt: `${YESTERDAY}T14:00:00Z`,
  },
];

export const INITIAL_JOB_OPENINGS: JobOpening[] = [
  {
    id: 'job-1',
    jobTitle: 'Sales Executive',
    department: 'HR Recruitment',
    vacancies: 10,
    filledPositions: 4,
    salaryRange: '₹20,000 - ₹28,000 + Incentives',
    jobLocation: 'Sector 62, Noida',
    experience: '1-3 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-30',
    status: 'Urgent',
  },
  {
    id: 'job-2',
    jobTitle: 'Telecaller',
    department: 'BKD Recruitment',
    vacancies: 15,
    filledPositions: 8,
    salaryRange: '₹16,000 - ₹22,000 + Incentives',
    jobLocation: 'Sector 62, Noida',
    experience: '0-2 Years',
    hrResponsible: 'Shivani',
    hiringDeadline: '2026-09-25',
    status: 'Open',
  },
  {
    id: 'job-3',
    jobTitle: 'HR Executive',
    department: 'HR Recruitment',
    vacancies: 2,
    filledPositions: 1,
    salaryRange: '₹22,000 - ₹28,000',
    jobLocation: 'Sector 62, Noida',
    experience: '1-2 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-20',
    status: 'Open',
  },
  {
    id: 'job-4',
    jobTitle: 'Team Leader',
    department: 'BKD Recruitment',
    vacancies: 3,
    filledPositions: 1,
    salaryRange: '₹32,000 - ₹40,000',
    jobLocation: 'Sector 62, Noida',
    experience: '3-5 Years',
    hrResponsible: 'Shivani',
    hiringDeadline: '2026-09-18',
    status: 'Urgent',
  },
  {
    id: 'job-5',
    jobTitle: 'Digital Marketing Executive',
    department: 'HR Recruitment',
    vacancies: 2,
    filledPositions: 0,
    salaryRange: '₹25,000 - ₹35,000',
    jobLocation: 'Sector 62, Noida',
    experience: '2-4 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-30',
    status: 'Open',
  },
  {
    id: 'job-6',
    jobTitle: 'Back Office Executive',
    department: 'HR Recruitment',
    vacancies: 4,
    filledPositions: 2,
    salaryRange: '₹18,000 - ₹24,000',
    jobLocation: 'Sector 62, Noida',
    experience: '1-2 Years',
    hrResponsible: 'Nandani',
    hiringDeadline: '2026-09-22',
    status: 'Open',
  },
];

export const INITIAL_SOURCE_AD_SPENDS: SourceAdSpend[] = [
  { source: 'Meta Ads', adSpend: 35000 },
  { source: 'Facebook', adSpend: 15000 },
  { source: 'Instagram', adSpend: 18000 },
  { source: 'WhatsApp', adSpend: 5000 },
  { source: 'Indeed', adSpend: 22000 },
  { source: 'Naukri', adSpend: 28000 },
  { source: 'Apna', adSpend: 16000 },
  { source: 'WorkIndia', adSpend: 12000 },
  { source: 'Referral', adSpend: 4000 },
  { source: 'Walk-in', adSpend: 0 },
  { source: 'Data Vendor', adSpend: 15000 },
  { source: 'Existing Database', adSpend: 0 },
  { source: 'Other', adSpend: 2000 },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    candidateId: 'ESL-2026-005',
    candidateName: 'Kunal Chauhan',
    action: 'Status Change',
    performedBy: 'Shivani',
    previousValue: 'Interview Conducted',
    newValue: 'Selected',
    timestamp: `${TODAY}T11:35:00Z`,
    details: 'Selected after evaluating technical and TL leadership round',
  },
  {
    id: 'log-2',
    candidateId: 'ESL-2026-004',
    candidateName: 'Ritu Sen',
    action: 'Status Change',
    performedBy: 'Nandani',
    previousValue: 'Interview Scheduled',
    newValue: 'Interview Confirmed',
    timestamp: `${TODAY}T09:30:00Z`,
    details: 'Candidate confirmed presence via WhatsApp call',
  },
  {
    id: 'log-3',
    candidateId: 'ESL-2026-001',
    candidateName: 'Rahul Sharma',
    action: 'Created',
    performedBy: 'Nandani',
    newValue: 'New Lead',
    timestamp: `${TODAY}T09:30:00Z`,
    details: 'Lead generated from Meta Ads campaign',
  },
  {
    id: 'log-4',
    candidateId: 'ESL-2026-008',
    candidateName: 'Megha Gupta',
    action: 'Marked Active',
    performedBy: 'Shivani',
    previousValue: 'Joined',
    newValue: 'Active Joining',
    timestamp: '2026-08-26T17:00:00Z',
    details: 'Completed 7 working days with regular attendance. Verified by TL.',
  },
];

export const DEFAULT_ROLE_PERMISSIONS: RolePermissionsMap = {
  'Super Admin': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'users',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'Director / Management': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'users',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'HR Head': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'companies',
    'departments',
    'targets',
    'permissions',
    'import-export',
    'reports',
    'templates',
    'audit',
    'database',
  ],
  'Team Leader': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'targets',
    'import-export',
    'reports',
    'templates',
  ],
  'HR Executive': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'import-export',
    'templates',
  ],
  'Recruiter': [
    'dashboard',
    'candidates',
    'followups',
    'interviews',
    'joining',
    'offer-letters',
    'terms-conditions',
    'jobs',
    'import-export',
    'templates',
  ],
  'Interviewer': [
    'dashboard',
    'interviews',
    'candidates',
    'jobs',
    'terms-conditions',
  ],
};

export const INITIAL_TERMS_CLAUSES: TermsClause[] = [
  {
    id: 'tc-1',
    clauseNumber: '1.0',
    category: 'Probation & Confirmation',
    title: 'Probationary Period & Evaluation',
    content: 'The employee shall be on probation for an initial period of 90 (ninety) calendar days from the Date of Joining. During this period, performance, discipline, adherence to operational calling targets, and team alignment will be reviewed on a continuous monthly basis. The company reserves the absolute right to extend the probation period or dispense with services if benchmark standards are not satisfactorily met.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-2',
    clauseNumber: '2.0',
    category: 'Working Hours & Attendance',
    title: 'Operating Hours, Shifts & Biometric Attendance',
    content: 'Standard operational working hours are Monday through Saturday from 9:30 AM to 6:30 PM with a designated 45-minute lunch break. Punctuality is strictly enforced; daily attendance must be marked via the biometric sensor or registered mobile ATS application. Three unexcused tardy arrivals exceeding 15 minutes within a calendar month shall result in the forfeiture of half a day of casual leave.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-3',
    clauseNumber: '3.0',
    category: 'Compensation & Incentives',
    title: 'Payroll Disbursement Cycle & Target-Linked Incentives',
    content: 'Salary is disbursed monthly on or before the 7th calendar day following the payroll cycle directly into the registered bank account. Remuneration is subject to all statutory deductions including TDS, Employee Provident Fund (EPF), Employee State Insurance (ESIC), and Professional Tax where applicable. Variable performance incentives are calculated strictly based on verified active candidate joinings sustaining beyond the 7-day threshold.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-4',
    clauseNumber: '4.0',
    category: 'Code of Conduct',
    title: 'Professional Integrity, Workplace Decorum & POSH Policy',
    content: 'The employee agrees to observe the highest standards of professional conduct, truthfulness, and decorum at all times. The company enforces strict zero-tolerance towards sexual harassment, verbal abuse, hate speech, insubordination, or discrimination in strict accordance with the Prevention of Sexual Harassment of Women at Workplace (POSH) Act 2013.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-5',
    clauseNumber: '5.0',
    category: 'Confidentiality & NDA',
    title: 'Proprietary Candidate Databases, Client Data & Non-Disclosure',
    content: 'The employee shall maintain absolute confidentiality regarding candidate resumes, mobile numbers, WhatsApp transcripts, client contracts, commercial recruitment fee structures, and internal candidate pipelining metrics. All such materials remain exclusive trade secrets of Essential Soul Lifestyle Pvt Ltd and must never be extracted, photographed, forwarded, or utilized outside company business.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-6',
    clauseNumber: '6.0',
    category: 'Leave & Time Off',
    title: 'Leave Accrual & Prior Approval Guidelines',
    content: 'Subsequent to successful confirmation post-probation, the employee is entitled to 18 (eighteen) days of paid leave annually, accrued at 1.5 days per completed calendar month. Any planned absence must be submitted in the recruitment portal at least 48 hours in advance and sanctioned in writing by the Team Leader or Department Head. Unsanctioned absence exceeding 3 consecutive days will be considered job abandonment.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Nandani (HR Head)',
  },
  {
    id: 'tc-7',
    clauseNumber: '7.0',
    category: 'Termination & Notice',
    title: 'Notice Period, Separation Formalities & Full and Final Settlement',
    content: 'During the probationary period, either party may terminate this employment contract by providing 15 (fifteen) calendar days notice in writing or gross salary in lieu thereof. Upon confirmation, the notice period shall be 30 (thirty) calendar days. The employee must complete a formal handover of all pending candidate pipeline leads, client files, and company equipment prior to release of Full & Final (F&F) settlement.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Aditya Mathur (Director)',
  },
  {
    id: 'tc-8',
    clauseNumber: '8.0',
    category: 'Onboarding Documents',
    title: 'Credential Verification & Mandatory Submission Checklist',
    content: 'This offer of employment is contingent upon prompt receipt and background verification of mandatory documents: self-attested copies of Aadhaar Card, PAN Card, Graduation/Post-Graduation Degree & Final Marksheet, Relieving/Experience Letter from prior employer, last 3 months salary slips/bank statements, and 3 passport-sized color photographs.',
    isMandatoryInOffer: true,
    isActive: true,
    updatedAt: '2026-09-01T09:00:00Z',
    updatedBy: 'Shivani (HR Executive)',
  },
];

export const INITIAL_OFFER_LETTERS: OfferLetter[] = [
  {
    id: 'OFR-2026-001',
    candidateId: 'ESL-2026-005',
    candidateName: 'Kunal Chauhan',
    candidateEmail: 'kunal.c@gmail.com',
    candidatePhone: '+91 98111 22334',
    candidateAddress: 'H.No 45, Sector 22, Noida, Gautam Buddha Nagar, UP - 201301',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    companyLegalName: 'Essential Soul Lifestyle Private Limited',
    companyAddress: 'Plot A-40, ITHUM Tower, Block A, Sector 62, Noida, UP - 201309',
    companyCin: 'U74999UP2022PTC168921',
    companyGstin: '09AAECE1234F1Z5',
    department: 'HR Recruitment',
    designation: 'Senior Recruitment Specialist',
    employmentType: 'Full-Time',
    workLocation: 'Noida Office (Sector 62)',
    reportingManager: 'Nandani (HR Head)',
    offerDate: '2026-09-02',
    joiningDate: '2026-09-12',
    validityDate: '2026-09-09',
    annualCtc: 480000,
    monthlyGross: 40000,
    basicSalary: 20000,
    hra: 10000,
    specialAllowance: 10000,
    performanceIncentive: 5000,
    monthlyInHand: 37600,
    probationMonths: 3,
    noticePeriodDays: 30,
    status: 'Issued',
    authorizedSignatoryName: 'Aditya Mathur',
    authorizedSignatoryTitle: 'Director & CEO',
    selectedClauseIds: ['tc-1', 'tc-2', 'tc-3', 'tc-4', 'tc-5', 'tc-6', 'tc-7', 'tc-8'],
    notes: 'Selected after evaluating technical and TL leadership round. Candidate accepted compensation verbally.',
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-02T10:00:00Z',
  },
  {
    id: 'OFR-2026-002',
    candidateId: 'ESL-2026-004',
    candidateName: 'Ritu Sen',
    candidateEmail: 'ritu.sen@gmail.com',
    candidatePhone: '+91 98765 43213',
    candidateAddress: 'Flat 302, Green Valley Apartments, Indirapuram, Ghaziabad, UP',
    companyId: 'comp-2',
    companyName: 'BKD Retail & Lifestyle Pvt Ltd',
    companyLegalName: 'BKD Lifestyle & Retail Private Limited',
    companyAddress: 'B-12, Sector 63, Near Electronic City Metro, Noida, UP - 201301',
    companyCin: 'U52100DL2023PTC189432',
    companyGstin: '07AABCB9876K1Z2',
    department: 'BKD Recruitment',
    designation: 'Outbound Tele-Recruiter',
    employmentType: 'Full-Time',
    workLocation: 'Noida Office (Sector 63)',
    reportingManager: 'Shivani (HR Executive)',
    offerDate: '2026-09-04',
    joiningDate: '2026-09-15',
    validityDate: '2026-09-10',
    annualCtc: 300000,
    monthlyGross: 25000,
    basicSalary: 12500,
    hra: 6250,
    specialAllowance: 6250,
    performanceIncentive: 3000,
    monthlyInHand: 23200,
    probationMonths: 3,
    noticePeriodDays: 15,
    status: 'Draft',
    authorizedSignatoryName: 'Aditya Mathur',
    authorizedSignatoryTitle: 'Managing Director',
    selectedClauseIds: ['tc-1', 'tc-2', 'tc-3', 'tc-4', 'tc-5', 'tc-7', 'tc-8'],
    notes: 'Draft offer letter ready for internal management approval.',
    createdAt: '2026-09-04T15:00:00Z',
    updatedAt: '2026-09-04T15:00:00Z',
  },
  {
    id: 'OFR-2026-003',
    candidateId: 'ESL-2026-008',
    candidateName: 'Megha Gupta',
    candidateEmail: 'megha.g@gmail.com',
    candidatePhone: '+91 98222 33445',
    candidateAddress: 'Tower 4, Apt 804, Gaur City 1, Greater Noida West, UP',
    companyId: 'comp-1',
    companyName: 'Essential Soul Lifestyle Pvt Ltd',
    companyLegalName: 'Essential Soul Lifestyle Private Limited',
    companyAddress: 'Plot A-40, ITHUM Tower, Block A, Sector 62, Noida, UP - 201309',
    companyCin: 'U74999UP2022PTC168921',
    companyGstin: '09AAECE1234F1Z5',
    department: 'HR Recruitment',
    designation: 'Talent Acquisition Executive',
    employmentType: 'Full-Time',
    workLocation: 'Noida Office (Sector 62)',
    reportingManager: 'Nandani (HR Head)',
    offerDate: '2026-08-12',
    joiningDate: '2026-08-19',
    validityDate: '2026-08-16',
    annualCtc: 360000,
    monthlyGross: 30000,
    basicSalary: 15000,
    hra: 7500,
    specialAllowance: 7500,
    performanceIncentive: 4000,
    monthlyInHand: 28100,
    probationMonths: 3,
    noticePeriodDays: 30,
    status: 'Joined',
    authorizedSignatoryName: 'Aditya Mathur',
    authorizedSignatoryTitle: 'Director & CEO',
    selectedClauseIds: ['tc-1', 'tc-2', 'tc-3', 'tc-4', 'tc-5', 'tc-6', 'tc-7', 'tc-8'],
    notes: 'Candidate joined on 19th Aug 2026 and successfully achieved Active Joining status.',
    createdAt: '2026-08-12T11:00:00Z',
    updatedAt: '2026-08-19T09:30:00Z',
  },
];
